[package]
name = "lfu"
version = "0.1.0"
authors = ["NavyaZaveri"]
edition = "2018"
description="An LFU cache implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_hash_set = "0.1.3"

